# -*- coding: utf-8 -*-
"""hw3_Quick-Sort

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15szow7i_EZBjQubkPOrezW9qjUNlCXJT
"""

def quick_sort(array, start, end):
    if start >= end:
        return

    pivot_index = start
    pivot = array[pivot_index]
    left = start
    right = end

    print(f"QuickSort called on: {array[start:end+1]}")

    while left != right:
        # 從右邊開始往左找第一個比 pivot 小的
        while array[right] >= pivot and left < right:
            right -= 1
        # 從左邊開始往右找第一個比 pivot 大的
        while array[left] <= pivot and left < right:
            left += 1
        if left < right:
            print(f"  Swapping left={left}({array[left]}), right={right}({array[right]})")
            array[left], array[right] = array[right], array[left]

    print(f"  Swapping pivot_index={pivot_index}({array[pivot_index]}), right={right}({array[right]})")
    array[pivot_index], array[right] = array[right], array[pivot_index]

    print(f"  Result after partition: {array[start:end+1]}\n")

    quick_sort(array, start, right - 1)
    quick_sort(array, right + 1, end)


# Demo
demo_array = [33, 67, 8, 13, 54, 119, 3, 84, 25, 41]
print("Original array:", demo_array)
quick_sort(demo_array, 0, len(demo_array) - 1)
print("Sorted array:  ", demo_array)